BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_ALARM ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_AOI ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_COATING1 ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_COATING2 ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_COATINGREVIEW ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_COATINGVISION ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_DOWNLOAD ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_EOL ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_ERROR ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_FCT ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_ICT ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_LCR ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_LOWCURRENT ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_MAOI ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_MARKING ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_MOUNTER ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_PROCESS ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_REFLOW_01 ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_REFLOW_02 ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_SELECTIVE ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_SPI ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_SPI_VD ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_VISION_LEGACY ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
  EXECUTE IMMEDIATE 'ALTER TABLE LOG_VISION_NATIVE ADD (ACTUAL_DATE DATE, SHIFT_CODE VARCHAR2(2 BYTE), ZONE_CODE VARCHAR2(2 BYTE))';
END;
/
